=== elbosso/elbosso.github.io/resources/sQLshell/EXAMPLE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:XMLExport:sQLshell" xmlns:ts="urn:XMLExport:sQLshell" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">
<xs:element name="sQLshell" type="ts:sQLshellType">
<xs:key name="EXAMPLEIDKey">
<xs:selector xpath="./ts:EXAMPLE/ts:EXAMPLE_row"/>
<xs:field xpath="ts:ID"/>
</xs:key>
<xs:annotation>
<xs:appinfo source="sQLshell:INDEXINFO?table=EXAMPLE&amp;name=SYS_PK_109">ID</xs:appinfo>
</xs:annotation>
<xs:keyref name="ADDRESS.PERSON_ID" refer="ts:EXAMPLEIDKey">
<xs:selector xpath="./ts:ADDRESS/ts:ADDRESS_row"/>
<xs:field xpath="ts:PERSON_ID"/>
</xs:keyref>
<xs:key name="ADDRESSIDKey">
<xs:selector xpath="./ts:ADDRESS/ts:ADDRESS_row"/>
<xs:field xpath="ts:ID"/>
</xs:key>
<xs:annotation>
<xs:appinfo source="sQLshell:INDEXINFO?table=ADDRESS&amp;name=SYS_PK_144">ID</xs:appinfo>
</xs:annotation>
<xs:annotation>
<xs:appinfo source="sQLshell:INDEXINFO?table=ADDRESS&amp;name=SYS_IDX_145">PERSON_ID</xs:appinfo>
</xs:annotation>
</xs:element>
<xs:complexType name="sQLshellType">
<xs:sequence>
<xs:element minOccurs="0" name="EXAMPLE" type="ts:EXAMPLETable"/>
<xs:element minOccurs="0" name="ADDRESS" type="ts:ADDRESSTable"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="EXAMPLETable">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="EXAMPLE_row" type="ts:EXAMPLErowType"/>
</xs:sequence>
</xs:complexType>
<xs:simpleType name="string255Type">
<xs:restriction base="xs:string">
<xs:maxLength value="255"/>
</xs:restriction>
</xs:simpleType>
<xs:complexType name="EXAMPLErowType">
<xs:sequence>
<xs:element maxOccurs="1" minOccurs="0" name="AGE" type="xs:int"/>
<xs:element maxOccurs="1" minOccurs="0" name="EXPERIENCE" type="xs:int"/>
<xs:element maxOccurs="1" minOccurs="1" name="ID" type="xs:int"/>
<xs:element maxOccurs="1" minOccurs="0" name="NAME" type="ts:string255Type"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="ADDRESSTable">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="ADDRESS_row" type="ts:ADDRESSrowType"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="ADDRESSrowType">
<xs:sequence>
<xs:element maxOccurs="1" minOccurs="1" name="ID" type="xs:int"/>
<xs:element maxOccurs="1" minOccurs="1" name="PERSON_ID" type="xs:int"/>
<xs:element maxOccurs="1" minOccurs="0" name="STREET" type="ts:string255Type"/>
<xs:element maxOccurs="1" minOccurs="0" name="TOWN" type="ts:string255Type"/>
<xs:element maxOccurs="1" minOccurs="1" name="ZIP" type="xs:decimal"/>
</xs:sequence>
</xs:complexType>
</xs:schema>

=== elbosso/elbosso.github.io/resources/sQLshell/EXAMPLE_PART1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ts:sQLshell xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			 xsi:schemaLocation="urn:XMLExport:sQLshell EXAMPLE.xsd" 
			 xmlns:ts="urn:XMLExport:sQLshell" 
			 xmlns:xi="http://www.w3.org/2001/XInclude"
			 xmlns="sQLshell">
<xi:include href="artificial.xml"/>
<ts:EXAMPLE>
<ts:EXAMPLE_row>
<ts:AGE>29</ts:AGE>
<ts:EXPERIENCE>5</ts:EXPERIENCE>
<ts:ID>6</ts:ID>
<ts:NAME><![CDATA[Penny]]></ts:NAME>
</ts:EXAMPLE_row>
<ts:EXAMPLE_row>
<ts:AGE>43</ts:AGE>
<ts:EXPERIENCE>1</ts:EXPERIENCE>
<ts:ID>7</ts:ID>
<ts:NAME><![CDATA[Bettie]]></ts:NAME>
</ts:EXAMPLE_row>
<ts:EXAMPLE_row>
<ts:AGE>26</ts:AGE>
<ts:EXPERIENCE>8</ts:EXPERIENCE>
<ts:ID>8</ts:ID>
<ts:NAME><![CDATA[Missie]]></ts:NAME>
</ts:EXAMPLE_row>
</ts:EXAMPLE>
<ts:ADDRESS>
<ts:ADDRESS_row>
<ts:ID>-2147483648</ts:ID>
<ts:PERSON_ID>3</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter der Deich-Gasse]]></ts:STREET>
<ts:TOWN><![CDATA[Hohen-Mehllohe]]></ts:TOWN>
<ts:ZIP>9284</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483647</ts:ID>
<ts:PERSON_ID>6</ts:PERSON_ID>
<ts:STREET><![CDATA[Unterm hohen Stadion]]></ts:STREET>
<ts:TOWN><![CDATA[Neu-Radegast]]></ts:TOWN>
<ts:ZIP>1703</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483646</ts:ID>
<ts:PERSON_ID>3</ts:PERSON_ID>
<ts:STREET><![CDATA[Giraffenberg]]></ts:STREET>
<ts:TOWN><![CDATA[Klein-Dornweiler]]></ts:TOWN>
<ts:ZIP>5379</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483645</ts:ID>
<ts:PERSON_ID>2</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben dem größten Ulmen-Ufer]]></ts:STREET>
<ts:TOWN><![CDATA[Ziesenstedt]]></ts:TOWN>
<ts:ZIP>32531</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483644</ts:ID>
<ts:PERSON_ID>1</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter der hellen Festhalle]]></ts:STREET>
<ts:TOWN><![CDATA[Groß-Saalgast]]></ts:TOWN>
<ts:ZIP>31254</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483643</ts:ID>
<ts:PERSON_ID>8</ts:PERSON_ID>
<ts:STREET><![CDATA[Hasen-Straße]]></ts:STREET>
<ts:TOWN><![CDATA[Altenwittenwald]]></ts:TOWN>
<ts:ZIP>4025</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483642</ts:ID>
<ts:PERSON_ID>1</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben dem Grafen-Ufer]]></ts:STREET>
<ts:TOWN><![CDATA[Überelbwinden]]></ts:TOWN>
<ts:ZIP>13534</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483641</ts:ID>
<ts:PERSON_ID>7</ts:PERSON_ID>
<ts:STREET><![CDATA[Vorm neuen Tal]]></ts:STREET>
<ts:TOWN><![CDATA[Unteruhlwald]]></ts:TOWN>
<ts:ZIP>24076</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483640</ts:ID>
<ts:PERSON_ID>6</ts:PERSON_ID>
<ts:STREET><![CDATA[Vor der neuen Linde]]></ts:STREET>
<ts:TOWN><![CDATA[Altenbreitenhübel]]></ts:TOWN>
<ts:ZIP>21147</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483639</ts:ID>
<ts:PERSON_ID>8</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter der Adlerstraße]]></ts:STREET>
<ts:TOWN><![CDATA[Ober-Steinfurt]]></ts:TOWN>
<ts:ZIP>10600</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483638</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter dem Lava-Ufer]]></ts:STREET>
<ts:TOWN><![CDATA[Altenroßheide]]></ts:TOWN>
<ts:ZIP>22842</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483637</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter der  Fabrik-Allee]]></ts:STREET>
<ts:TOWN><![CDATA[Ottenkirchen]]></ts:TOWN>
<ts:ZIP>3941</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483636</ts:ID>
<ts:PERSON_ID>4</ts:PERSON_ID>
<ts:STREET><![CDATA[Feuerufer]]></ts:STREET>
<ts:TOWN><![CDATA[Elbwegen]]></ts:TOWN>
<ts:ZIP>6159</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483635</ts:ID>
<ts:PERSON_ID>4</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter dem verzauberten Kloster-Platz]]></ts:STREET>
<ts:TOWN><![CDATA[Überelbin]]></ts:TOWN>
<ts:ZIP>25532</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483634</ts:ID>
<ts:PERSON_ID>7</ts:PERSON_ID>
<ts:STREET><![CDATA[Feuerberg]]></ts:STREET>
<ts:TOWN><![CDATA[Neufriedrichmarschen]]></ts:TOWN>
<ts:ZIP>2244</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483633</ts:ID>
<ts:PERSON_ID>7</ts:PERSON_ID>
<ts:STREET><![CDATA[Beim alten Hotel]]></ts:STREET>
<ts:TOWN><![CDATA[Bad Ober-Greifenwegen]]></ts:TOWN>
<ts:ZIP>31774</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483631</ts:ID>
<ts:PERSON_ID>8</ts:PERSON_ID>
<ts:STREET><![CDATA[Beim vergessenen Königinnenberg]]></ts:STREET>
<ts:TOWN><![CDATA[Ober-Nauntal]]></ts:TOWN>
<ts:ZIP>22810</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483630</ts:ID>
<ts:PERSON_ID>1</ts:PERSON_ID>
<ts:STREET><![CDATA[Im großen Findling]]></ts:STREET>
<ts:TOWN><![CDATA[St. Neu-Falkendorf]]></ts:TOWN>
<ts:ZIP>4697</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483629</ts:ID>
<ts:PERSON_ID>1</ts:PERSON_ID>
<ts:STREET><![CDATA[Auf der verlassenen Gasse]]></ts:STREET>
<ts:TOWN><![CDATA[Oberroßtal]]></ts:TOWN>
<ts:ZIP>24452</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483628</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben dem vergessenen Rathaus]]></ts:STREET>
<ts:TOWN><![CDATA[Überborsweiler]]></ts:TOWN>
<ts:ZIP>12168</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483627</ts:ID>
<ts:PERSON_ID>3</ts:PERSON_ID>
<ts:STREET><![CDATA[Auf dem  Kaiserufer]]></ts:STREET>
<ts:TOWN><![CDATA[Klein-Schönfelde vorm Damm]]></ts:TOWN>
<ts:ZIP>3556</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>-2147483626</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter dem oberen Friedhof]]></ts:STREET>
<ts:TOWN><![CDATA[Niederkrimdorf]]></ts:TOWN>
<ts:ZIP>13334</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>22535402</ts:ID>
<ts:PERSON_ID>8</ts:PERSON_ID>
<ts:STREET><![CDATA[Unterm ältesten Findling]]></ts:STREET>
<ts:TOWN><![CDATA[Westerleben]]></ts:TOWN>
<ts:ZIP>13584</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>83878366</ts:ID>
<ts:PERSON_ID>1</ts:PERSON_ID>
<ts:STREET><![CDATA[Auf der  Abtei]]></ts:STREET>
<ts:TOWN><![CDATA[Unter-Breitenhausen]]></ts:TOWN>
<ts:ZIP>27782</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>107142479</ts:ID>
<ts:PERSON_ID>2</ts:PERSON_ID>
<ts:STREET><![CDATA[Vor der hohen Schule]]></ts:STREET>
<ts:TOWN><![CDATA[Walderoda]]></ts:TOWN>
<ts:ZIP>688</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>113737718</ts:ID>
<ts:PERSON_ID>2</ts:PERSON_ID>
<ts:STREET><![CDATA[Geier-Allee]]></ts:STREET>
<ts:TOWN><![CDATA[Kleinfrankbeck]]></ts:TOWN>
<ts:ZIP>20505</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>121412842</ts:ID>
<ts:PERSON_ID>1</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter der kleinen Hauptstraße]]></ts:STREET>
<ts:TOWN><![CDATA[Groß-Rockhagen]]></ts:TOWN>
<ts:ZIP>24480</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>180243020</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Vorm verlassenen Aquedukt]]></ts:STREET>
<ts:TOWN><![CDATA[Alten-Wolfsdruf]]></ts:TOWN>
<ts:ZIP>32265</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>248229680</ts:ID>
<ts:PERSON_ID>3</ts:PERSON_ID>
<ts:STREET><![CDATA[In der Mätressengasse]]></ts:STREET>
<ts:TOWN><![CDATA[Ober-Probstgast]]></ts:TOWN>
<ts:ZIP>7800</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>293506319</ts:ID>
<ts:PERSON_ID>7</ts:PERSON_ID>
<ts:STREET><![CDATA[In dem Pinguin-Ufer]]></ts:STREET>
<ts:TOWN><![CDATA[Unter-Mittelloh]]></ts:TOWN>
<ts:ZIP>18838</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>299311781</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Löwenstraße]]></ts:STREET>
<ts:TOWN><![CDATA[Alt-Brunsdorf]]></ts:TOWN>
<ts:ZIP>5522</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>304997867</ts:ID>
<ts:PERSON_ID>5</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben der kleinen Grotte]]></ts:STREET>
<ts:TOWN><![CDATA[Altendarmhaff]]></ts:TOWN>
<ts:ZIP>14368</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>449360722</ts:ID>
<ts:PERSON_ID>8</ts:PERSON_ID>
<ts:STREET><![CDATA[Unter dem  Ameisenweg]]></ts:STREET>
<ts:TOWN><![CDATA[Klein-Westerbeck]]></ts:TOWN>
<ts:ZIP>24200</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>468326616</ts:ID>
<ts:PERSON_ID>4</ts:PERSON_ID>
<ts:STREET><![CDATA[Mäusegasse]]></ts:STREET>
<ts:TOWN><![CDATA[Neu-Herrenau]]></ts:TOWN>
<ts:ZIP>13911</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>599471610</ts:ID>
<ts:PERSON_ID>6</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben dem historischen Gemeindehaus]]></ts:STREET>
<ts:TOWN><![CDATA[Treuen-Testbeck]]></ts:TOWN>
<ts:ZIP>23926</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>605415894</ts:ID>
<ts:PERSON_ID>6</ts:PERSON_ID>
<ts:STREET><![CDATA[Beim Theaterberg]]></ts:STREET>
<ts:TOWN><![CDATA[Altenmittelstein]]></ts:TOWN>
<ts:ZIP>14899</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>652593112</ts:ID>
<ts:PERSON_ID>6</ts:PERSON_ID>
<ts:STREET><![CDATA[In der neuen Mühle]]></ts:STREET>
<ts:TOWN><![CDATA[Unter-Ebermarschen]]></ts:TOWN>
<ts:ZIP>21356</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>738072380</ts:ID>
<ts:PERSON_ID>3</ts:PERSON_ID>
<ts:STREET><![CDATA[Schul-Straße]]></ts:STREET>
<ts:TOWN><![CDATA[Bellburg]]></ts:TOWN>
<ts:ZIP>502</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>798199502</ts:ID>
<ts:PERSON_ID>2</ts:PERSON_ID>
<ts:STREET><![CDATA[Unterm dunklen Telegrafenamt]]></ts:STREET>
<ts:TOWN><![CDATA[Altprobstau]]></ts:TOWN>
<ts:ZIP>18213</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>808888753</ts:ID>
<ts:PERSON_ID>4</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben der Theaterstraße]]></ts:STREET>
<ts:TOWN><![CDATA[Treuen-Reinsheim]]></ts:TOWN>
<ts:ZIP>8195</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>907425663</ts:ID>
<ts:PERSON_ID>3</ts:PERSON_ID>
<ts:STREET><![CDATA[Neben der hohen Bank]]></ts:STREET>
<ts:TOWN><![CDATA[Neuwidderkamp]]></ts:TOWN>
<ts:ZIP>19135</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>938940054</ts:ID>
<ts:PERSON_ID>7</ts:PERSON_ID>
<ts:STREET><![CDATA[In der ältesten Festhalle]]></ts:STREET>
<ts:TOWN><![CDATA[Neu-Uhlkamp]]></ts:TOWN>
<ts:ZIP>27550</ts:ZIP>
</ts:ADDRESS_row>
<ts:ADDRESS_row>
<ts:ID>1013598250</ts:ID>
<ts:PERSON_ID>6</ts:PERSON_ID>
